version: "2"
services:

  node:
    image: mineplex:latest
    hostname: node
    command: mineplex-node
    ports:
      - 9732:9732
    expose:
      - '8732'
    volumes:
      - ./node_data:/var/run/tezos/node
      - ./client_data:/var/run/tezos/client
    restart: on-failure

  baker:
    image: mineplex:latest
    hostname: baker
    environment:
      - PROTOCOL=002-Pt4xzupC
    command: mineplex-baker
    links:
      - node
    volumes:
      - ./node_data:/var/run/tezos/node
      - ./client_data:/var/run/tezos/client
    restart: on-failure

  endorser:
    image: mineplex:latest
    hostname: endorser
    environment:
      - PROTOCOL=002-Pt4xzupC
    command: mineplex-endorser
    links:
      - node
    volumes:
      - ./node_data:/var/run/tezos/node
      - ./client_data:/var/run/tezos/client
    restart: on-failure

  accuser:
    image: mineplex:latest
    hostname: accuser
    environment:
      - PROTOCOL=002-Pt4xzupC
    command: mineplex-accuser
    links:
      - node
    volumes:
      - ./node_data:/var/run/tezos/node
      - ./client_data:/var/run/tezos/client
    restart: on-failure